# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-03-01 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_kg',
            field=models.CharField(max_length=50, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435(\u043a\u044b\u0440\u0433.)'),
        ),
        migrations.AddField(
            model_name='food',
            name='description_kg',
            field=models.CharField(max_length=500, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435(\u043a\u044b\u0440\u0433.)'),
        ),
        migrations.AddField(
            model_name='food',
            name='title_kg',
            field=models.CharField(max_length=50, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435(\u043a\u044b\u0440\u0433.)'),
        ),
    ]
